# Generated by Django 2.2.12 on 2020-05-18 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Forum',
            new_name='Discussion',
        ),
        migrations.AlterModelOptions(
            name='discussion',
            options={'verbose_name': 'discussion', 'verbose_name_plural': 'discussions'},
        ),
        migrations.AddField(
            model_name='topic',
            name='discussion',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='forums.Discussion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='topic',
            name='moderator',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='accounts.Professional'),
        ),
    ]
