# Generated by Django 2.2.12 on 2020-05-19 02:43

from django.db import migrations, models
import django.db.models.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0003_auto_20200519_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='topic',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.fields.related.ForeignKey, related_name='posts', to='forums.Topic'),
            preserve_default=False,
        ),
    ]
