# Generated by Django 2.2.12 on 2020-05-11 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_album_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='caption',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
