# Generated by Django 2.2.12 on 2020-05-21 03:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_auto_20200501_0524'),
        ('classifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default=uuid.uuid1, unique=True)),
                ('status', models.BooleanField(default=False)),
                ('type', models.CharField(blank=True, choices=[('Invite', 'Invite'), ('Inquiry', 'Inquiry')], max_length=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_requests_received', to='accounts.Professional')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_requests_sent', to='accounts.Professional')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=80, unique=True)),
                ('name', models.CharField(blank=True, max_length=60, unique=True)),
                ('access', models.CharField(blank=True, choices=[('Public', 'Public'), ('Private', 'Private')], max_length=9)),
                ('is_active', models.BooleanField(default=True)),
                ('black_list', models.ManyToManyField(blank=True, related_name='rooms_forbidden', to='accounts.Professional')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='classifications.Category')),
                ('host', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='accounts.Professional')),
                ('members', models.ManyToManyField(blank=True, related_name='room_memberships', to='accounts.Professional')),
                ('tags', models.ManyToManyField(blank=True, related_name='rooms', to='classifications.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default=uuid.uuid1, unique=True)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='conversations.Room')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='accounts.Professional')),
            ],
        ),
    ]
