# Generated by Django 2.2.12 on 2020-05-21 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='details',
            field=models.TextField(blank=True, default=''),
        ),
    ]
