# Generated by Django 2.2.12 on 2020-05-21 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_room_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='black_list',
            field=models.ManyToManyField(blank=True, related_name='rooms_forbidden', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='room',
            name='host',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='room',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='room_memberships', to=settings.AUTH_USER_MODEL),
        ),
    ]
