# Generated by Django 2.2.12 on 2020-05-22 04:14

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0006_auto_20200522_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=mdeditor.fields.MDTextField(),
        ),
    ]
